sudo: required
language: c
before_install:		
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"		
  - sleep 3		
  - export DISPLAY=:1.0		
install:
  - ./tests/install.sh
script:
  - arduino --verify --board arduino:avr:uno wharehauora-sensor/wharehauora-sensor.ino
